/**
 * i18n — Locale detection and user-facing string bundles for Scout hooks.
 * Code, comments, and file structure remain English.
 * User-facing advice output follows the user's system locale.
 *
 * Supported locales: en (default), nl, de, fr, es, zh
 * Override via SCOUT_LANG env var (e.g. SCOUT_LANG=nl) for testing or explicit config.
 */

const STRINGS = {
  en: {
    // advisor-post-tool-use: suggestion format
    skillTip: 'Skill tip:',
    what: 'What:',
    whyNow: 'Why now:',
    useText: (name) => `Use: ${name.startsWith('/') ? 'Invoke' : 'Launch agent'} ${name}`,
    alsoAvailable: 'also available:',
    skillTips: 'Skill tips:',
    combinedAdvice: 'Combined advice:',
    and: 'and',

    // advisor-post-tool-use: reason texts
    reasonTesting: (file) => `Working on test files${file ? ` (${file})` : ''}.`,
    reasonApi: (file) => `Editing API/route files${file ? ` (${file})` : ''}.`,
    reasonDatabase: (file) => `Working with database code${file ? ` (${file})` : ''}.`,
    reasonSecurity: (file) => `Editing security-related code${file ? ` (${file})` : ''} with auth/token/password handling.`,
    reasonFrontend: (file) => `Working on frontend components${file ? ` (${file})` : ''}.`,
    reasonDocker: (file) => `Editing Docker configuration${file ? ` (${file})` : ''}.`,
    reasonBuildError: () => 'Build errors detected in output.',
    reasonGitWorkflow: () => 'A complex git operation is in progress.',
    reasonDataScience: (file) => `Working with data science code${file ? ` (${file})` : ''}.`,
    reasonDefault: () => 'Relevant patterns detected in current work.',

    // scout-session-start: briefing
    existingProfile: (date) => `Existing profile found (last session: ${date})`,
    recommendedSkills: 'Recommended skills:',
    recommendedAgents: 'Recommended agents:',
    otherTooling: 'Other tooling:',
    scoutTip: 'Tip: /scout for full scan | /scout:eval for mid-session check | /scout:bootstrap for deep analysis',

    // scout-session-start: CLAUDE.md section
    autoGenerated: (date, lang) => `*Auto-generated by Claude Scout — ${date} (${lang} project)*`,
    skillsInvoke: 'Skills — invoke when relevant:',
    agentsLaunch: 'Agents — launch proactively:',
    sectionHeader: 'Scout Recommendations',

    // scout-session-start: usage triggers
    triggerTdd: 'for new features, bug fixes, or refactoring',
    triggerSecurity: 'for auth, API endpoints, or user input handling',
    triggerCodeReview: 'after significant code changes',
    triggerCodingStandard: 'when making code changes',
    triggerApiDesign: 'when designing API endpoints',
    triggerBuildError: 'on build failures or type errors',
    triggerRefactor: 'for refactoring or dead code cleanup',
    triggerDatabase: 'for database queries or schema changes',
    triggerDebug: 'when resolving bugs',
    triggerDefault: 'use when relevant',
  },

  nl: {
    // advisor-post-tool-use: suggestion format
    skillTip: 'Skill tip:',
    what: 'Wat:',
    whyNow: 'Waarom nu:',
    useText: (name) => `Gebruik: ${name.startsWith('/') ? 'Roep aan' : 'Lanceer agent'} ${name}`,
    alsoAvailable: 'ook beschikbaar:',
    skillTips: 'Skill tips:',
    combinedAdvice: 'Gecombineerd advies:',
    and: 'en',

    // advisor-post-tool-use: reason texts
    reasonTesting: (file) => `Bezig met test bestanden${file ? ` (${file})` : ''}.`,
    reasonApi: (file) => `API/route bestanden bewerken${file ? ` (${file})` : ''}.`,
    reasonDatabase: (file) => `Bezig met databasecode${file ? ` (${file})` : ''}.`,
    reasonSecurity: (file) => `Beveiligingsgerelateerde code bewerken${file ? ` (${file})` : ''} met auth/token/wachtwoord verwerking.`,
    reasonFrontend: (file) => `Bezig met frontend componenten${file ? ` (${file})` : ''}.`,
    reasonDocker: (file) => `Docker configuratie bewerken${file ? ` (${file})` : ''}.`,
    reasonBuildError: () => 'Build fouten gedetecteerd in output.',
    reasonGitWorkflow: () => 'Een complexe git operatie is bezig.',
    reasonDataScience: (file) => `Bezig met data science code${file ? ` (${file})` : ''}.`,
    reasonDefault: () => 'Relevante patronen gedetecteerd in huidig werk.',

    // scout-session-start: briefing
    existingProfile: (date) => `Bestaand profiel gevonden (laatste sessie: ${date})`,
    recommendedSkills: 'Aanbevolen skills:',
    recommendedAgents: 'Aanbevolen agents:',
    otherTooling: 'Overige tooling:',
    scoutTip: 'Tip: /scout voor volledige scan | /scout:eval voor mid-session evaluatie | /scout:bootstrap voor diepte-analyse',

    // scout-session-start: CLAUDE.md section
    autoGenerated: (date, lang) => `*Automatisch gegenereerd door Claude Scout — ${date} (${lang} project)*`,
    skillsInvoke: 'Skills — roep aan wanneer relevant:',
    agentsLaunch: 'Agents — lanceer proactief:',
    sectionHeader: 'Scout Aanbevelingen',

    // scout-session-start: usage triggers
    triggerTdd: 'bij nieuwe features, bug fixes of refactoring',
    triggerSecurity: 'bij auth, API endpoints of user input verwerking',
    triggerCodeReview: 'na significante codewijzigingen',
    triggerCodingStandard: 'bij codewijzigingen',
    triggerApiDesign: 'bij het ontwerpen van API endpoints',
    triggerBuildError: 'bij build failures of type errors',
    triggerRefactor: 'bij refactoring of dead code cleanup',
    triggerDatabase: 'bij database queries of schema wijzigingen',
    triggerDebug: 'bij het oplossen van bugs',
    triggerDefault: 'gebruik wanneer relevant',
  },

  de: {
    skillTip: 'Skill-Tipp:',
    what: 'Was:',
    whyNow: 'Warum jetzt:',
    useText: (name) => `Verwenden: ${name.startsWith('/') ? 'Aufrufen' : 'Agent starten'} ${name}`,
    alsoAvailable: 'auch verfügbar:',
    skillTips: 'Skill-Tipps:',
    combinedAdvice: 'Kombinierter Hinweis:',
    and: 'und',

    reasonTesting: (file) => `Arbeit an Testdateien${file ? ` (${file})` : ''}.`,
    reasonApi: (file) => `API/Route-Dateien bearbeiten${file ? ` (${file})` : ''}.`,
    reasonDatabase: (file) => `Arbeit mit Datenbankcode${file ? ` (${file})` : ''}.`,
    reasonSecurity: (file) => `Sicherheitsrelevanten Code bearbeiten${file ? ` (${file})` : ''} mit Auth/Token/Passwort-Verarbeitung.`,
    reasonFrontend: (file) => `Arbeit an Frontend-Komponenten${file ? ` (${file})` : ''}.`,
    reasonDocker: (file) => `Docker-Konfiguration bearbeiten${file ? ` (${file})` : ''}.`,
    reasonBuildError: () => 'Build-Fehler in der Ausgabe erkannt.',
    reasonGitWorkflow: () => 'Ein komplexer Git-Vorgang läuft.',
    reasonDataScience: (file) => `Arbeit mit Data-Science-Code${file ? ` (${file})` : ''}.`,
    reasonDefault: () => 'Relevante Muster in der aktuellen Arbeit erkannt.',

    existingProfile: (date) => `Vorhandenes Profil gefunden (letzte Sitzung: ${date})`,
    recommendedSkills: 'Empfohlene Skills:',
    recommendedAgents: 'Empfohlene Agents:',
    otherTooling: 'Weitere Tools:',
    scoutTip: 'Tipp: /scout für vollständigen Scan | /scout:eval für Zwischen-Check | /scout:bootstrap für Tiefenanalyse',

    autoGenerated: (date, lang) => `*Automatisch generiert von Claude Scout — ${date} (${lang}-Projekt)*`,
    skillsInvoke: 'Skills — bei Bedarf aufrufen:',
    agentsLaunch: 'Agents — proaktiv starten:',
    sectionHeader: 'Scout-Empfehlungen',

    triggerTdd: 'bei neuen Features, Bugfixes oder Refactoring',
    triggerSecurity: 'bei Auth, API-Endpunkten oder Benutzereingaben',
    triggerCodeReview: 'nach größeren Codeänderungen',
    triggerCodingStandard: 'bei Codeänderungen',
    triggerApiDesign: 'beim Entwerfen von API-Endpunkten',
    triggerBuildError: 'bei Build-Fehlern oder Typfehlern',
    triggerRefactor: 'beim Refactoring oder Bereinigen von totem Code',
    triggerDatabase: 'bei Datenbankabfragen oder Schemaänderungen',
    triggerDebug: 'beim Beheben von Bugs',
    triggerDefault: 'verwenden wenn relevant',
  },

  fr: {
    skillTip: 'Conseil skill :',
    what: 'Quoi :',
    whyNow: 'Pourquoi maintenant :',
    useText: (name) => `Utiliser : ${name.startsWith('/') ? 'Invoquer' : 'Lancer l\'agent'} ${name}`,
    alsoAvailable: 'aussi disponible :',
    skillTips: 'Conseils skills :',
    combinedAdvice: 'Conseil combiné :',
    and: 'et',

    reasonTesting: (file) => `Travail sur les fichiers de test${file ? ` (${file})` : ''}.`,
    reasonApi: (file) => `Modification des fichiers API/routes${file ? ` (${file})` : ''}.`,
    reasonDatabase: (file) => `Travail avec le code de base de données${file ? ` (${file})` : ''}.`,
    reasonSecurity: (file) => `Modification du code lié à la sécurité${file ? ` (${file})` : ''} avec gestion auth/token/mot de passe.`,
    reasonFrontend: (file) => `Travail sur les composants frontend${file ? ` (${file})` : ''}.`,
    reasonDocker: (file) => `Modification de la configuration Docker${file ? ` (${file})` : ''}.`,
    reasonBuildError: () => 'Erreurs de build détectées dans la sortie.',
    reasonGitWorkflow: () => 'Une opération Git complexe est en cours.',
    reasonDataScience: (file) => `Travail avec du code data science${file ? ` (${file})` : ''}.`,
    reasonDefault: () => 'Patterns pertinents détectés dans le travail actuel.',

    existingProfile: (date) => `Profil existant trouvé (dernière session : ${date})`,
    recommendedSkills: 'Skills recommandés :',
    recommendedAgents: 'Agents recommandés :',
    otherTooling: 'Autres outils :',
    scoutTip: 'Astuce : /scout pour scan complet | /scout:eval pour vérification en cours | /scout:bootstrap pour analyse approfondie',

    autoGenerated: (date, lang) => `*Généré automatiquement par Claude Scout — ${date} (projet ${lang})*`,
    skillsInvoke: 'Skills — invoquer quand pertinent :',
    agentsLaunch: 'Agents — lancer de manière proactive :',
    sectionHeader: 'Recommandations Scout',

    triggerTdd: 'pour les nouvelles fonctionnalités, corrections de bugs ou refactoring',
    triggerSecurity: 'pour l\'auth, les endpoints API ou la gestion des entrées utilisateur',
    triggerCodeReview: 'après des modifications de code significatives',
    triggerCodingStandard: 'lors de modifications de code',
    triggerApiDesign: 'lors de la conception d\'endpoints API',
    triggerBuildError: 'lors d\'erreurs de build ou de type',
    triggerRefactor: 'pour le refactoring ou le nettoyage de code mort',
    triggerDatabase: 'pour les requêtes de base de données ou modifications de schéma',
    triggerDebug: 'lors de la résolution de bugs',
    triggerDefault: 'utiliser quand pertinent',
  },

  es: {
    skillTip: 'Consejo skill:',
    what: 'Qué:',
    whyNow: 'Por qué ahora:',
    useText: (name) => `Usar: ${name.startsWith('/') ? 'Invocar' : 'Lanzar agente'} ${name}`,
    alsoAvailable: 'también disponible:',
    skillTips: 'Consejos skills:',
    combinedAdvice: 'Consejo combinado:',
    and: 'y',

    reasonTesting: (file) => `Trabajando en archivos de prueba${file ? ` (${file})` : ''}.`,
    reasonApi: (file) => `Editando archivos API/rutas${file ? ` (${file})` : ''}.`,
    reasonDatabase: (file) => `Trabajando con código de base de datos${file ? ` (${file})` : ''}.`,
    reasonSecurity: (file) => `Editando código relacionado con seguridad${file ? ` (${file})` : ''} con manejo de auth/token/contraseña.`,
    reasonFrontend: (file) => `Trabajando en componentes frontend${file ? ` (${file})` : ''}.`,
    reasonDocker: (file) => `Editando configuración Docker${file ? ` (${file})` : ''}.`,
    reasonBuildError: () => 'Errores de build detectados en la salida.',
    reasonGitWorkflow: () => 'Una operación Git compleja está en progreso.',
    reasonDataScience: (file) => `Trabajando con código de ciencia de datos${file ? ` (${file})` : ''}.`,
    reasonDefault: () => 'Patrones relevantes detectados en el trabajo actual.',

    existingProfile: (date) => `Perfil existente encontrado (última sesión: ${date})`,
    recommendedSkills: 'Skills recomendados:',
    recommendedAgents: 'Agentes recomendados:',
    otherTooling: 'Otras herramientas:',
    scoutTip: 'Tip: /scout para escaneo completo | /scout:eval para verificación intermedia | /scout:bootstrap para análisis profundo',

    autoGenerated: (date, lang) => `*Generado automáticamente por Claude Scout — ${date} (proyecto ${lang})*`,
    skillsInvoke: 'Skills — invocar cuando sea relevante:',
    agentsLaunch: 'Agentes — lanzar proactivamente:',
    sectionHeader: 'Recomendaciones Scout',

    triggerTdd: 'para nuevas funcionalidades, correcciones de bugs o refactoring',
    triggerSecurity: 'para auth, endpoints API o manejo de entrada de usuario',
    triggerCodeReview: 'después de cambios de código significativos',
    triggerCodingStandard: 'al realizar cambios de código',
    triggerApiDesign: 'al diseñar endpoints API',
    triggerBuildError: 'en errores de build o de tipos',
    triggerRefactor: 'para refactoring o limpieza de código muerto',
    triggerDatabase: 'para consultas de base de datos o cambios de esquema',
    triggerDebug: 'al resolver bugs',
    triggerDefault: 'usar cuando sea relevante',
  },

  zh: {
    skillTip: '技能提示：',
    what: '内容：',
    whyNow: '为何现在：',
    useText: (name) => `使用：${name.startsWith('/') ? '调用' : '启动 Agent'} ${name}`,
    alsoAvailable: '也可用：',
    skillTips: '技能提示：',
    combinedAdvice: '综合建议：',
    and: '和',

    reasonTesting: (file) => `正在处理测试文件${file ? `（${file}）` : ''}。`,
    reasonApi: (file) => `正在编辑 API/路由文件${file ? `（${file}）` : ''}。`,
    reasonDatabase: (file) => `正在处理数据库代码${file ? `（${file}）` : ''}。`,
    reasonSecurity: (file) => `正在编辑安全相关代码${file ? `（${file}）` : ''}，涉及 auth/token/密码处理。`,
    reasonFrontend: (file) => `正在处理前端组件${file ? `（${file}）` : ''}。`,
    reasonDocker: (file) => `正在编辑 Docker 配置${file ? `（${file}）` : ''}。`,
    reasonBuildError: () => '在输出中检测到构建错误。',
    reasonGitWorkflow: () => '正在进行复杂的 Git 操作。',
    reasonDataScience: (file) => `正在处理数据科学代码${file ? `（${file}）` : ''}。`,
    reasonDefault: () => '在当前工作中检测到相关模式。',

    existingProfile: (date) => `找到现有配置文件（上次会话：${date}）`,
    recommendedSkills: '推荐技能：',
    recommendedAgents: '推荐 Agent：',
    otherTooling: '其他工具：',
    scoutTip: '提示：/scout 完整扫描 | /scout:eval 中途检查 | /scout:bootstrap 深度分析',

    autoGenerated: (date, lang) => `*由 Claude Scout 自动生成 — ${date}（${lang} 项目）*`,
    skillsInvoke: '技能 — 相关时调用：',
    agentsLaunch: 'Agent — 主动启动：',
    sectionHeader: 'Scout 建议',

    triggerTdd: '用于新功能、Bug 修复或重构',
    triggerSecurity: '用于 auth、API 端点或用户输入处理',
    triggerCodeReview: '在重大代码更改后',
    triggerCodingStandard: '进行代码更改时',
    triggerApiDesign: '设计 API 端点时',
    triggerBuildError: '出现构建错误或类型错误时',
    triggerRefactor: '用于重构或清理死代码',
    triggerDatabase: '用于数据库查询或 schema 更改',
    triggerDebug: '解决 Bug 时',
    triggerDefault: '相关时使用',
  },
};

/**
 * Detect the user's preferred language from environment variables.
 * Priority: SCOUT_LANG > LANG > LANGUAGE > LC_ALL > fallback 'en'
 */
function detectLanguage() {
  const raw = process.env.SCOUT_LANG ||
              process.env.LANG ||
              process.env.LANGUAGE ||
              process.env.LC_ALL ||
              '';
  const code = raw.split(/[_.\-]/)[0].toLowerCase();
  return STRINGS[code] ? code : 'en';
}

/** Returns the string bundle for the detected (or overridden) locale. */
function getStrings() {
  return STRINGS[detectLanguage()];
}

module.exports = { getStrings, detectLanguage, STRINGS };
